modLoader="javafml"
loaderVersion="[47,)"

license="All Rights Reserved"
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
showAsResourcePack=false
clientSideOnly=false

[[mods]]
modId="cosmosportals_liveview"
version="1.20.1-1.0.0"
displayName="Cosmos Portals Live View"
description="Adds a live view option to Cosmos Portals surfaces"


[[dependencies.cosmosportals_liveview]]
modId="cosmosportals"
mandatory=true
versionRange="[7.5.0.0,)"
ordering="NONE"
side="BOTH"
